version: '3.9'

services:
  encoder:
    image: jrottenberg/ffmpeg:4.1-ubuntu
    volumes:
      - type: bind
        source: ../input/
        target: /tmp/workdir/input/
      - type: bind
        source: ../output/
        target: /tmp/workdir/output/
    entrypoint:
      - "sh"
    tty: true

  image:
    image: nginx:1.26.0-bookworm
    ports:
      - "2005:80"
    volumes:
      - type: bind
        source: ../src
        target: /usr/share/nginx/html
      - type: bind
        source: ../input
        target: /usr/share/nginx/html/resource
    tty: true