version: '3.9'

services:
  youtube-art-track-builder-core:
    container_name: youtube-art-track-builder-core
    image: jrottenberg/ffmpeg:4.1-ubuntu
    volumes:
      - type: bind
        source: ../input/
        target: /tmp/workdir/input/
      - type: bind
        source: ../output/
        target: /tmp/workdir/output/
    entrypoint:
      - "sh"
    tty: true

  youtube-art-track-image:
    container_name: youtube-art-track-image
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: ../src
        target: /usr/share/nginx/html
      - type: bind
        source: ../input
        target: /usr/share/nginx/html/resource
    tty: true